"""
PROJECT: The Sales Data Analyzer (Simulator)

Goal: Build a high-performance sales analytics simulator using NumPy.

Requirements:

1. Data Generation:
   - Imagine we have data for 5 different retail stores (Store 0 to Store 4).
   - Each store sells 3 product categories: "Electronics", "Clothing", "Home Goods".
   - We track daily sales for these products over a 7-day week.
   - This can be represented as a 3D NumPy array of shape (5, 3, 7):
     - Dimension 0: Stores (5)
     - Dimension 1: Products (3)
     - Dimension 2: Days (7)

2. Analytics Tasks (Implement using Vectorized NumPy Operations):
   - 'total_revenue(data)': Returns the sum of all sales across all stores, products, and days.
   - 'store_revenue(data)': Returns a 1D array of length 5, showing the total revenue for each store.
   - 'product_revenue(data)': Returns a 1D array of length 3, showing the total revenue for each product category across all stores.
   - 'daily_averages(data)': Returns a 1D array of length 7, showing the average sales for each day of the week.
   - 'best_store(data)': Identifies the index of the store with the highest revenue.
   - 'apply_tax(data, rate)': Returns a copy of the data with a tax rate (e.g., 0.08 for 8%) deducted from all sales.

3. Testing and Simulation:
   - Generate random sales data using np.random.randint(100, 1000, size=(5, 3, 7)) representing dollar sales.
   - Run the analytical functions and print a formatted dashboard.

Real-World Logic:
- Global corporations like Walmart or Amazon process terabytes of sales data daily. Standard Python lists would collapse under the load, but NumPy allows them to query, slice, and analyze massive volumes of financial transactions in milliseconds.
"""

import numpy as np


# ============================================================
# Sales Data Analyzer (Simulator)
# ============================================================

# Stores:
# 0 = Store A
# 1 = Store B
# 2 = Store C
# 3 = Store D
# 4 = Store E

# TODO: Implement the Sales Data Analyzer


PRODUCTS = ["Electronics", "Clothing", "Home Goods"]
DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


# ============================================================
# Analytics Functions
# ============================================================

def total_revenue(data):
    """
    Sum of all sales across stores, products, and days.
    """
    return np.sum(data)


def store_revenue(data):
    """
    Revenue generated by each store.
    Shape returned: (5,)
    """
    return np.sum(data, axis=(1, 2))


def product_revenue(data):
    """
    Revenue generated by each product category.
    Shape returned: (3,)
    """
    return np.sum(data, axis=(0, 2))


def daily_averages(data):
    """
    Average sales for each day across all stores/products.
    Shape returned: (7,)
    """
    return np.round(np.mean(data, axis=(0, 1)), 2)


def best_store(data):
    """
    Returns index of store with highest revenue.
    """
    return np.argmax(store_revenue(data))


def apply_tax(data, rate):
    """
    Deduct tax from all sales values.
    Returns a NEW array (does not modify original).
    """
    taxed_data = data * (1 - rate)
    return np.round(taxed_data, 2)


# ============================================================
# Dashboard Display
# ============================================================

def print_dashboard(data):
    print("=" * 60)
    print(" SALES DATA ANALYZER DASHBOARD ")
    print("=" * 60)

    # Total revenue
    print(f"\nTotal Revenue: ${total_revenue(data):,}")

    # Store revenue
    print("\nRevenue by Store:")
    store_totals = store_revenue(data)

    for i, revenue in enumerate(store_totals):
        print(f"  Store {i}: ${revenue:,}")

    # Product revenue
    print("\nRevenue by Product Category:")
    product_totals = product_revenue(data)

    for product, revenue in zip(PRODUCTS, product_totals):
        print(f"  {product:<12}: ${revenue:,}")

    # Daily averages
    print("\nAverage Daily Sales:")
    averages = daily_averages(data)

    for day, avg in zip(DAYS, averages):
        print(f"  {day}: ${avg}")

    # Best store
    best = best_store(data)
    print(f"\nBest Performing Store: Store {best}")

    # Tax example
    taxed = apply_tax(data, 0.08)

    print("\nSample Taxed Data (8% deduction applied):")
    print(taxed)

    print("\n" + "=" * 60)


# ============================================================
# Main Simulation
# ============================================================

if __name__ == "__main__":

    # Seed for reproducibility
    np.random.seed(42)

    print("Generating random sales data...")
    
    # Shape: (5 stores, 3 products, 7 days)
    sales_data = np.random.randint(
        100,
        1000,
        size=(5, 3, 7)
    )

    print("\nSales Data Shape:", sales_data.shape)

    # Run dashboard
    print_dashboard(sales_data)